### ISSUE TITLE
Why so many third-party libraries is this project depended on?

### ISSUE THREAD

**Issue by faywong** [nomisRev/FasterLayoutsWithAnko#1]
It spends so many time to sync down these libraries, are they all used?

**Comment by nomisRev** [comment]
Syncing the libraries shouldn't take that long at all on a decent network connection. And they should be cached by gradle anyhow, so they only need to get synced once. Anyhow, I don't use all of them in this example. But I forgot to clear them out, although this is by no means a large set of dependencies at all.

**Comment by faywong** [comment]
OK. Got it. It's on earth a China specific problem.
